# Generated by Django 5.2.8 on 2025-11-08 09:50

import app.db_models.tools.set_media_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('json_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Coins',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Country Name')),
                ('code_alpha_2', models.CharField(blank=True, db_index=True, max_length=2, null=True, unique=True)),
                ('code_alpha_3', models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True)),
                ('emoji_flag', models.CharField(blank=True, max_length=4, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country_flags/')),
                ('raw_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raw Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DBConnectionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_connections', models.IntegerField()),
                ('idle_connections', models.IntegerField()),
                ('idle_in_transaction', models.IntegerField()),
            ],
            options={
                'verbose_name': 'DB Connection Snapshot',
                'verbose_name_plural': 'DB Connection Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Image Name')),
                ('name_page', models.CharField(max_length=255, verbose_name='Image Name Page')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='site_images')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('usage', models.CharField(blank=True, default='', max_length=100)),
                ('scheme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('image', models.ImageField(upload_to='site_images/social')),
            ],
            options={
                'verbose_name_plural': 'images Social',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='ImageCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=app.db_models.tools.set_media_path.image_upload_path)),
                ('scheme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.coin')),
            ],
            options={
                'verbose_name_plural': 'images',
                'ordering': ('pk',),
            },
        ),
    ]
