# Generated by Django 5.2.8 on 2025-11-09 17:34

import app.db_models.tools.set_media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='json_data',
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=app.db_models.tools.set_media_path.default_image_upload_path),
        ),
        migrations.DeleteModel(
            name='ImageCoin',
        ),
    ]
