# Generated by Django 5.2.8 on 2025-11-09 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_coin_json_data_coin_image_delete_imagecoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Labels',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='buys_h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='buys_h24',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coin',
            name='format_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='gugu_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='gugu_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='liquidity_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_presale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='popularity_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='popularity_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_1h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_24h',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='security_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='security_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='security_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='sells_h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='sells_h24',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='source_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='volume_btc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='volume_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='votes24h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='coins', to='app.category'),
        ),
        migrations.AddField(
            model_name='coin',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='coins', to='app.label'),
        ),
    ]
