# Generated by Django 5.2.8 on 2025-11-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_label_coin_buys_h1_coin_buys_h24_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='format_price',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
