# Generated by Django 5.2.8 on 2025-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_coin_format_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='format_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
