# Generated by Django 5.2.8 on 2025-11-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_coin_format_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='buys_h1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='buys_h24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='gugu_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='liquidity_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='popularity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='security_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='sells_h1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='sells_h24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='votes24h',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
