# Generated by Django 5.2.8 on 2025-11-10 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_coin_buys_h1_alter_coin_buys_h24_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorerChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Explorer Chain',
                'verbose_name_plural': 'Explorer Chains',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='full_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('chain_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='chain_images/')),
                ('id_chain_gopluslabs', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('explorer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain', to='app.explorerchain')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotedCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False, verbose_name='Promotion is Permanent')),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='app.coin')),
            ],
            options={
                'verbose_name': 'Promoted Coin',
                'verbose_name_plural': 'Promoted Coin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('basic', models.BooleanField(default=False)),
                ('chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_address', to='app.chain')),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_address', to='app.coin')),
            ],
            options={
                'verbose_name': 'Contract Address',
                'verbose_name_plural': 'Contract Addresses',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['basic', 'coin', 'chain'], name='idx_basic_coin')],
            },
        ),
    ]
