# Generated by Django 5.2.8 on 2025-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_explorerchain_coin_full_desc_chain_promotedcoin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('pair_url', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=18, max_digits=64, null=True)),
                ('format_price', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Base Coin',
                'verbose_name_plural': 'Base Coins',
                'ordering': ['id'],
            },
        ),
    ]
