# Generated by Django 5.2.8 on 2025-11-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_basecoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='chain_id',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='id_chain_gopluslabs',
        ),
        migrations.AddField(
            model_name='coin',
            name='chain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='app.chain'),
        ),
        migrations.AddField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='ContractAddress',
        ),
    ]
