# Generated by Django 5.2.8 on 2025-11-13 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_chain_chain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin', to='app.chain'),
        ),
    ]
