# Generated by Django 5.2.8 on 2025-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_coin_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='contract_address',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
