# Generated by Django 5.2.8 on 2025-11-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_coin_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CoinSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('whitepaper', 'Whitepaper'), ('reddit', 'Reddit'), ('twitter', 'Twitter'), ('gecko', 'Gecko'), ('discord', 'Discord'), ('market', 'Market'), ('website', 'Website'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('medium', 'Medium'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.imagesocial')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='app.coin')),
            ],
            options={
                'verbose_name': 'Socials',
                'verbose_name_plural': 'Socials',
                'ordering': ['id'],
            },
        ),
    ]
