# Generated by Django 5.2.8 on 2025-11-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_coin_is_published_coinsocial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinsocial',
            old_name='Image',
            new_name='image',
        ),
    ]
