# Generated by Django 5.2.8 on 2025-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_image_coinsocial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='security_rank',
        ),
        migrations.AlterField(
            model_name='coinsocial',
            name='name',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('whitepaper', 'Whitepaper'), ('reddit', 'Reddit'), ('twitter', 'Twitter(X)'), ('gecko', 'Gecko'), ('discord', 'Discord'), ('market', 'Market'), ('website', 'Website'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('medium', 'Medium'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=50, null=True),
        ),
    ]
