# Generated by Django 5.2.8 on 2025-12-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_coin_security_rank_alter_coinsocial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAndAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_rank', models.IntegerField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('audit_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auditprovider')),
                ('audit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auditstatus')),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_and_audit', to='app.coin')),
            ],
            options={
                'verbose_name_plural': 'Safety And Audit',
                'ordering': ('pk',),
            },
        ),
    ]
