# Generated by Django 5.2.8 on 2025-12-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auditprovider_auditstatus_safetyandaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetyandaudit',
            old_name='security_rank',
            new_name='security_score',
        ),
    ]
