# Generated by Django 5.2.8 on 2025-12-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_security_rank_safetyandaudit_security_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyandaudit',
            name='security_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
