# Generated by Django 5.2.8 on 2025-12-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_safetyandaudit_security_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Количество монет, находящихся в обращении', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='launch_price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Цена монеты на момент запуска', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Максимально возможное количество монет (лимит эмиссии)', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Общее количество существующих монет на данный момент', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='launch_date',
            field=models.DateField(blank=True, help_text='Дата запуска монеты', null=True),
        ),
    ]
