# Generated by Django 5.2.8 on 2025-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_coin_circulating_supply_coin_launch_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='gugu_rank',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='gugu_score',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='market_cap_rank',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='popularity_rank',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='popularity_score',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='popularity_updated_at',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='security_score',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='security_updated_at',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='source_page',
        ),
    ]
