# Generated by Django 5.2.8 on 2025-12-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_coin_gugu_rank_remove_coin_gugu_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='buys_h1',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='buys_h24',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='sells_h1',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='sells_h24',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='votes24h',
        ),
    ]
