# Generated by Django 5.2.8 on 2025-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_coin_buys_h1_remove_coin_buys_h24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='high_24h_price',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='low_24h_price',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
    ]
