# Generated by Django 5.2.8 on 2025-12-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_coin_high_24h_price_coin_low_24h_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='app.coin')),
            ],
            options={
                'verbose_name_plural': 'Coin Predictions',
                'ordering': ('created_at',),
            },
        ),
    ]
