# Generated by Django 5.2.8 on 2025-12-06 13:37

import app.db_models.tools.set_media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_coinprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=app.db_models.tools.set_media_path.default_image_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Team Coins',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='Команда проекта', related_name='coins', to='app.teamcoin'),
        ),
    ]
