# Generated by Django 5.2.8 on 2025-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_teamcoin_coin_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True),
        ),
    ]
