# Generated by Django 5.2.8 on 2025-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_coin_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinprediction',
            name='avg_price',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='coinprediction',
            name='max_price',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='coinprediction',
            name='min_price',
            field=models.DecimalField(decimal_places=18, max_digits=30),
        ),
    ]
