# Generated by Django 5.2.8 on 2025-12-11 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_coinprediction_avg_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPieChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Label Pie Charts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PieChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pie_charts', to='app.coin')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pie_charts', to='app.labelpiechart')),
            ],
            options={
                'verbose_name_plural': 'Pie Charts Datas',
                'ordering': ('pk',),
            },
        ),
    ]
